version: '3.8'
services:
    db:
        image: database
        build:
            context: ./backend/db/
            dockerfile: Dockerfile
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            PGDATA: /data/postgres
            PGUSER: admin
        volumes:
            - postgres:/data/postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "--quiet"]
            interval: 1s
            timeout: 5s
            retries: 10
    backend:
        image: backend
        build:
            context: ./backend/
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - backend:/var/usr/

volumes:
    postgres:
    backend: